### PR TITLE
BUG: Update GUI-parameter node connection on entering GUI

### LINKED ISSUE #22: GUI not updating correctly
Steps:
1. Load a saved scene
2. Open MarkupsToModel
3. If not already done, disable auto-update
4. Change between different types of curve, see that the GUI does not update unless you click on "Update"

### PR DESCRIPTION
**Pull request by tavaughan**
Should fix #22

### CODE REVIEW

**Review by lassoan — APPROVED** [review]
I preferred the original method name (it is not just reconnection but GUI update as well), but other than that the fix is good. If you strongly prefer the new method name then you can keep that, too.

**Comment by tavaughan** [comment]
Thanks I'll take another look tomorrow and then integrate the change into the PathReconstruction, TransformProcessor, CollectPoints, and FiducialRegistration modules.

**Comment by tavaughan** [comment]
updateGUIAndParameterNodeConnection

**Comment by lassoan** [comment]
In general, method names that contain multiple actions indicate design/conceptual error. I think the original method name was better, but if you don't find it good enough then we can keep thinking about better ones. You can also clarify things by improving the method's documentation.

**Pull request merged**
